notifications:
  slack:
    secure: K1XPQSE3k/OvUVEuX3+NZkts0DUJlIe8QdM9oJcDtaWrWZoBa/RIhQQKUETb919mKELXOELOlCPatmHAN8rUbBDDfBXV6HSHkhLo/udLaZBCMqVUG3pxzn54ENTK2LN20NpvTTUpgpS9CCazB8n9eBDnFkHgmL7YA4OF5dkEF3xsepO4X90vnt53FXOXzSdmlG2qYFPbSQbbe0dEfp+2RCSMalkojeQ/aB52R6E10ja35UvZlI5R4W1qWFbQvn5yg1i5ZNzaOwUC8ISrZChZmFC3xrNv5SW08GFpmDtlsqZw0lQpbPk9XP0woIxw8NOmvtEaCMQOWOhA2Ugl1B2c+W7YEwgab8xa3WhKLx6NYeIYOX389p2ctjdOC3KBttNZV4eMFmlZ7kbEQOaN0Sgxo69IuBf/9g5ChdchHUWkZ1KZbF5L9BO7VDsz0EKn8RV8g+mkM6+az9lUvXnnGTujPJSASV+nPa5f52tkMgfHr3vaimdN6vo6+a4hYO8qI5yKtMrM+m3a8ZJesOyw519ZgJsOF7LGcBUZGIS38PQxgsQH3KsZT/VMxQbuNLK2urh0Q1y/eoaH91rJg7Oc5dkCItZ5fjiggX7M9z3Sx5iJc8pvo/0qBcOvjHA1kZlVVJ0+Ut2uqUDYFV6oQz2ZMGV926kLj3qNG3mFBKqd+8TS8hc=
language: php
php:
  - 5.6
  - 7.0
before_install:
  - cd ..
  - git clone https://github.com/neos/flow-base-distribution.git
  - cd flow-base-distribution
  - git checkout 3.3.4
  - composer update --dev
  - composer require codeclimate/php-test-reporter:dev-master --dev
install:
  - mv ../SimplyAdmire.Oversight Packages/Application
script:
  - bin/phpunit -c Packages/Application/SimplyAdmire.Oversight/UnitTests.xml
  - bin/phpunit --stop-on-failure -c Packages/Application/SimplyAdmire.Oversight/UnitTests.xml --testsuite "SimplyAdmire.Oversight tests"