---

##
# Default route with just the package

-
  name: 'default with package'
  uriPattern: ''
  defaults:
    '@package':    'SimplyAdmire.Oversight'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true
